### ISSUE TITLE
File dialog keeps reopening in MS Edge

### ISSUE THREAD

**Issue by borismo** [lorem--ipsum/deep-float#3]
I will *not* take "why the heck do you use Edge?" as an answer.

Steps:

1. Click on the up arrow in the top right corner. File dialog shows up
2. Hit Esc key or click cancel
3. The dialog closes and reopens.

Have to kill the Edge process through Tasks Manager

**Comment by lorem--ipsum** [comment]
Making people give up on Microsoft's products is actually a feature, not a bug.

Har. Har.

Seriously though, I can't replicate the issue because I don't own a PC, so I guess the answer is : only supported browsers are Chrome and Firefox. It's a shame though, because I've heard Edge is almost usable.

**Comment by borismo** [comment]
"almost usable"... ^^

OK. Fair enough. Closing issue.
